eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: restaurant-service
    config:
        import: optional:configserver:http://localhost:8888
    data:
        mongodb:
            uri: mongodb+srv://urosrelicc:rACDvKWAv2HSKwsl@cluster0.pti2k.mongodb.net/food-order-app-spring?retryWrites=true&w=majority&appName=Cluster0
            database: food-order-app-spring
server:
    port: 8120