eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: AuthenticationFilter
        - id: auth-service
          uri: http://localhost:9898
          predicates:
            - Path=/api/v1/auth/**

        - id: category-service-auth
          uri: http://localhost:8110
          predicates:
            - Path=/api/v1/category/auth/**
          filters:
            - name: AuthenticationFilter
        - id: category-service
          uri: http://localhost:8110
          predicates:
            - Path=/api/v1/category/**
          filters: [ ]

        - id: food-service-auth
          uri: http://localhost:8100
          predicates:
            - Path=/api/v1/food/auth/**
          filters:
            - name: AuthenticationFilter
        - id: food-service
          uri: http://localhost:8100
          predicates:
            - Path=/api/v1/food/**
          filters: [ ]

        - id: restaurant-service-auth
          uri: http://localhost:8120
          predicates:
            - Path=/api/v1/restaurant/auth/**
          filters:
            - name: AuthenticationFilter
        - id: restaurant-service
          uri: http://localhost:8120
          predicates:
            - Path=/api/v1/restaurant/**
          filters: [ ]


server:
  port: 8222


