eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: AuthenticationFilter

        - id: auth-service
          uri: http://localhost:9898
          predicates:
            - Path=/api/v1/auth/**
          # No need for filters since it has security dependencies

        # Route with authentication for auth-specific paths
        - id: category-service-auth
          uri: http://localhost:8110
          predicates:
            - Path=/api/v1/category/auth/**
          filters:
            - name: AuthenticationFilter
        # Route without authentication for general categories paths
        - id: category-service
          uri: http://localhost:8110
          predicates:
            - Path=/api/v1/category/**
          filters: [ ] # No filters applied

        # Route with authentication for auth-specific paths
        - id: food-service-auth
          uri: http://localhost:8100
          predicates:
            - Path=/api/v1/food/auth/**
          filters:
            - name: AuthenticationFilter
        # Route without authentication for general food paths
        - id: category-service
          uri: http://localhost:8100
          predicates:
            - Path=/api/v1/food/**
          filters: [ ] # No filters applied

server:
  port: 8222


