eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://auth-service:9898
          predicates:
            - Path=/api/v1/auth/**

        - id: category-service-auth
          uri: http://category-service:8110
          predicates:
            - Path=/api/v1/category/auth/**
          filters:
            - name: AuthenticationFilter
        - id: category-service
          uri: http://category-service:8110
          predicates:
            - Path=/api/v1/category/**
          filters: [ ]

        - id: food-service-auth
          uri: http://food-service:8100
          predicates:
            - Path=/api/v1/food/auth/**
          filters:
            - name: AuthenticationFilter
        - id: food-service
          uri: http://food-service:8100
          predicates:
            - Path=/api/v1/food/**
          filters: [ ]

        - id: restaurant-service-auth
          uri: http://restaurant-service:8120
          predicates:
            - Path=/api/v1/restaurant/auth/**
          filters:
            - name: AuthenticationFilter
        - id: restaurant-service
          uri: http://restaurant-service:8120
          predicates:
            - Path=/api/v1/restaurant/**
          filters: [ ]

        - id: cart-service-auth
          uri: http://cart-service:8130
          predicates:
            - Path=/api/v1/cart/auth/**
          filters:
            - name: AuthenticationFilter
        - id: cart-service
          uri: http://cart-service:8130
          predicates:
            - Path=/api/v1/cart/**
          filters: [ ]


server:
  port: 8222


