eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: AuthenticationFilter
        - id: auth-service
          uri: http://localhost:9898
          predicates:
            - Path=/api/v1/auth/**
server:
  port: 8222


