eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/food-order-app-spring
      database: food-order-app-spring
security:
  jwt:
    secret: fa7f681d4597c77dd5d90aad3702162e6bc3d4a840f8e87ef6f8f56402d7b95c
    expiration: 3600000 # 1 hour
server:
  port: 9898